{"name": "Невозможно войти в систему, используя даные несуществующего курьера.", "status": "passed", "description": "Для проверки создается и удаляется курьер, под которым затем происходит попытка входа.Проверяется: ошибка == \"Учетная запись не найдена\" и статус код == 404.", "steps": [{"name": "Регистрация курьера и подготовка json", "status": "passed", "start": 1721097481468, "stop": 1721097482801}, {"name": "Удаление курьера", "status": "passed", "start": 1721097482801, "stop": 1721097485620}, {"name": "Отправка POST запроса для входа курьера в систему", "status": "passed", "start": 1721097485620, "stop": 1721097486907}, {"name": "Проверка: ошибка == 'Учетная запись не найдена'", "status": "passed", "start": 1721097486907, "stop": 1721097486907}, {"name": "Проверка: статус код == 404", "status": "passed", "start": 1721097486907, "stop": 1721097486907}], "start": 1721097481468, "stop": 1721097486908, "uuid": "e170ea8a-f866-4cbf-a79c-a77e7c9c138f", "historyId": "3ea887fdb1baedde027be71235a57f5f", "testCaseId": "3ea887fdb1baedde027be71235a57f5f", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_courier_non_existent_courier_cannot_login", "labels": [{"name": "suite", "value": "POST /api/v1/courier/login"}, {"name": "tag", "value": "@pytest.mark.usefixtures('cleanup_users')"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "C02DQ0GHMD6R"}, {"name": "thread", "value": "78646-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}